### ISSUE TITLE
README.debian in setup.cfg prevents RPM build

### ISSUE THREAD

**Issue by kazarmy** [nolta/biggles#59]
The reference to README.debian in [setup.cfg](https://github.com/nolta/biggles/blob/8191a0fec41705038e3dae395ebda62006e57234/setup.cfg) is preventing RPM builds via `python setup.py bdist_rpm`. Eventually, the following error message is shown:

```
...
+ cp -pr README.debian /home/<username>/tar/biggles-1.6.7/build/bdist.linux-i686/rpm/BUILDROOT/python2-biggles-1.6.7-1.i386/usr/share/doc/python2-biggles
cp: cannot stat 'README.debian': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.wX6jql (%doc)
```

Fix: Remove README.debian from setup.cfg.

**Comment by esheldon** [comment]
I removed README.debian from master

**Comment by beckermr** [comment]
Do we need to support RPM builds in the future? pip should work everywhere and it is easiest to maintain just a single build package.
